### PR TITLE
Add some cardmarket properties

### PR DESCRIPTION
**Pull request by CptSpaceToaster**
Most of these are nullable

### CODE REVIEW

**Comment by CptSpaceToaster** [comment]
I can rebase this ontop of the v2.0.0 branch if you'd like.

**Comment by acupoftee** [comment]
Yes, that would be fantastic. Thank you!

**Comment by CptSpaceToaster** [comment]
Hmmm... I wasn't signing up to rebase every commit you've made from `main` to `v2.0.0` on top of this change. And it doesn't even seem possible to do it cleanly right now, as that branch is +34 -24 commits out of sync.

There is no way to organize the code to look like this:
`[main]`->`[my commit to add Cardmarket fields]`->`[commits leading to v2.0.0]`

I didn't know where you were at with the v2.0.0 release, and was proposing that we'd close this MR, and replace it with a new MR that looked like:
`[main]`->`[v2.0.0]`->`[my commit to add Cardmarket fields in the newer structure]`

Which is totally doable... but when you merged this in, it cemented in the first part:
`[main]->[my commit to add Cardmarket fields]`

It's a heady amount of work to rebase `v2.0.0` on top of `main` to get this change in. Basically... what you're unintentionally asking for wasn't what I was offering. So at this point, I can still create an MR against `v2.0.0`, but it would introduce more weirdness and separate `main` from `v2.0.0` in ways that I wouldn't know how to cleanly resolve.

So would you like me to
1️⃣ Leave the mess as-is, and leave everything alone.
or
2️⃣ Make it messier, and have me create a new MR that adds in the fields for the cardmarket API against the `v2.0.0` branch.

**Comment by acupoftee** [comment]
I see. Leave it as is for now. I'll see what I can do to resolve it.

**Pull request merged**
